function Show-AnimatedMenu.Msfconsole {
    $msfCommands = @(
        @{ Command="use exploit/windows/smb/ms17_010_eternalblue"; Description="MS17-010 EternalBlue SMB istismarı." },
        @{ Command="use exploit/unix/ftp/proftpd_133c_backdoor"; Description="ProFTPD 1.3.3c backdoor FTP istismarı." },
        @{ Command="use auxiliary/scanner/portscan/tcp"; Description="TCP port taraması yapar." },
        @{ Command="use auxiliary/scanner/ftp/ftp_version"; Description="FTP versiyonunu tarar." },
        @{ Command="use auxiliary/scanner/ssh/ssh_version"; Description="SSH versiyonunu tarar." },
        @{ Command="use auxiliary/scanner/http/http_version"; Description="HTTP versiyonunu tarar." },
        @{ Command="use auxiliary/scanner/smb/smb_version"; Description="SMB versiyonunu tarar." },
        @{ Command="use auxiliary/scanner/snmp/snmp_login"; Description="SNMP login bilgilerini tarar." },
        @{ Command="use auxiliary/scanner/vnc/vnc_login"; Description="VNC login bilgilerini tarar." },
        @{ Command="use auxiliary/scanner/mssql/mssql_login"; Description="MSSQL login bilgilerini tarar." },
        @{ Command="use auxiliary/scanner/mysql/mysql_login"; Description="MySQL login bilgilerini tarar." },
        @{ Command="use auxiliary/scanner/oracle/oracle_login"; Description="Oracle login bilgilerini tarar." },
        @{ Command="use auxiliary/scanner/postgres/postgres_login"; Description="Postgres login bilgilerini tarar." },
        @{ Command="use exploit/multi/http/php_cgi_arg_injection"; Description="PHP CGI argüman enjeksiyonu istismarı." },
        @{ Command="use exploit/windows/http/rejetto_hfs_exec"; Description="Rejetto HFS komut yürütme istismarı." },
        @{ Command="use exploit/linux/http/advantech_webaccess_dashboard_exec"; Description="Advantech WebAccess Dashboard komut yürütme istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_shader_drawing_fill"; Description="Adobe Flash shader drawing fill istismarı." },
        @{ Command="use exploit/windows/misc/hp_imc_bims_downloadservlet_traversal"; Description="HP IMC BIMS Directory Traversal istismarı." },
        @{ Command="use exploit/windows/smtp/imap_subscribe"; Description="IMAP Subscribe istismarı." },
        @{ Command="use exploit/windows/ftp/vermillionftpd_port"; Description="VermillionFTPD Port istismarı." },
        @{ Command="use exploit/linux/samba/is_known_pipename"; Description="Samba pipename tespiti istismarı." },
        @{ Command="use exploit/linux/samba/samba_symlink_traversal"; Description="Samba Symlink Traversal istismarı." },
        @{ Command="use exploit/windows/ftp/3com_3cdaemon_ftp_user"; Description="3com 3cDaemon FTP User istismarı." },
        @{ Command="use exploit/unix/webapp/drupal_drupalgeddon2"; Description="Drupal Drupageddon 2 istismarı." },
        @{ Command="use exploit/multi/http/struts_code_exec_classloader"; Description="Apache Struts ClassLoader komut yürütme istismarı." },
        @{ Command="use exploit/unix/irc/unreal_ircd_3281_backdoor"; Description="UnrealIRCD 3.2.8.1 backdoor istismarı." },
        @{ Command="use exploit/windows/rdp/cve_2019_0708_bluekeep_rce"; Description="CVE-2019-0708 BlueKeep RCE istismarı." },
        @{ Command="use exploit/multi/handler"; Description="Multi-handler payload alıcısı." },
        @{ Command="use exploit/multi/fileformat/adobe_pdf_embedded_exe"; Description="Adobe PDF Embedded EXE istismarı." },
        @{ Command="use exploit/multi/ssh/sshexec"; Description="SSH Exec komut yürütme istismarı." },
        @{ Command="use auxiliary/dos/tcp/synflood"; Description="TCP SYN Flood DoS saldırısı." },
        @{ Command="use auxiliary/dos/udp/snmp_loop"; Description="SNMP Loop DoS saldırısı." },
        @{ Command="use auxiliary/dos/windows/smb/ms06_035_ftp"; Description="MS06-035 SMB FTP DoS saldırısı." },
        @{ Command="use auxiliary/dos/http/ms15_034_ulonglongadd"; Description="MS15-034 HTTP DoS saldırısı." },
        @{ Command="use auxiliary/dos/windows/rdp/ms12_020_maxchannelids"; Description="MS12-020 RDP DoS saldırısı." },
        @{ Command="use exploit/windows/smb/ms08_067_netapi"; Description="MS08-067 NetAPI istismarı." },
        @{ Command="use exploit/windows/smb/ms17_010_psexec"; Description="MS17-010 PsExec SMB istismarı." },
        @{ Command="use exploit/windows/browser/ms10_018_ie_behaviors"; Description="MS10-018 Internet Explorer behaviors istismarı." },
        @{ Command="use exploit/windows/browser/ms14_064_ole_code_execution"; Description="MS14-064 OLE kod yürütme istismarı." },
        @{ Command="use exploit/multi/http/struts2_content_type_ognl"; Description="Apache Struts2 Content-Type OGNL Injection istismarı." },
        @{ Command="use exploit/multi/http/tomcat_mgr_upload"; Description="Apache Tomcat Manager Upload istismarı." },
        @{ Command="use exploit/unix/webapp/phpmyadmin_3522_backdoor"; Description="phpMyAdmin 3.5.2.2 backdoor istismarı." },
        @{ Command="use exploit/windows/local/ms13_097_ie_registry_symlink"; Description="MS13-097 Internet Explorer registry symlink istismarı." },
        @{ Command="use exploit/windows/local/ms15_004_tswbproxy"; Description="MS15-004 TSWbProxy istismarı." },
        @{ Command="use exploit/windows/local/ms16_032_secondary_logon_handle_privesc"; Description="MS16-032 Secondary Logon Handle yetki yükseltme istismarı." },
        @{ Command="use exploit/windows/local/ms16_135_schema_update"; Description="MS16-135 Schema Update istismarı." },
        @{ Command="use exploit/windows/local/cve_2020_0787_bits"; Description="CVE-2020-0787 Windows BITS yetki yükseltme istismarı." },
        @{ Command="use exploit/multi/browser/java_signed_applet"; Description="Java Signed Applet komut yürütme istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_nellymoser_bof"; Description="Adobe Flash Nellymoser BOF istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_uncompress_zlib_uaf"; Description="Adobe Flash Uncompress Zlib UAF istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_mp4_cprt"; Description="Adobe Flash MP4 cprt istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_avm2"; Description="Adobe Flash AVM2 istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_shaderjob"; Description="Adobe Flash ShaderJob istismarı." },
        @{ Command="use exploit/windows/browser/adobe_flash_filters_type_confusion"; Description="Adobe Flash Filters Type Confusion istismarı." },
        @{ Command="use exploit/windows/browser/ms13_055_canchor"; Description="MS13-055 CAnchor istismarı." },
        @{ Command="use exploit/windows/browser/ms13_009_ie_slayoutrun"; Description="MS13-009 Internet Explorer SLayoutRun istismarı." },
        @{ Command="use exploit/windows/browser/ms14_012_cmarkup_uaf"; Description="MS14-012 CMarkup UAF istismarı." },
        @{ Command="use exploit/windows/browser/ms15_020_shortcut_icon_dllloader"; Description="MS15-020 Kısayol Simge DLL Yükleyici istismarı." },
        @{ Command="use exploit/windows/local/ms10_092_schelevator"; Description="MS10-092 SchedElevator istismarı." },
        @{ Command="use exploit/windows/local/ms11_080_mshtml_cobjectelement"; Description="MS11-080 mshtml CObjectElement istismarı." },
        @{ Command="use exploit/windows/local/ms13_005_hwpolicy"; Description="MS13-005 HWPolicy istismarı." },
        @{ Command="use exploit/windows/local/ms14_058_track_popup_menu"; Description="MS14-058 TrackPopupMenu istismarı." },
        @{ Command="use exploit/windows/local/ms14_070_tcpip_ioctl"; Description="MS14-070 tcpip IOCTL istismarı." },
        @{ Command="use exploit/windows/local/ms15_051_client_copy_image"; Description="MS15-051 ClientCopyImage istismarı." },
        @{ Command="use exploit/windows/local/ms16_016_webdav"; Description="MS16-016 WebDAV istismarı." },
        @{ Command="use exploit/windows/local/ms16_075_reflection"; Description="MS16-075 Reflection istismarı." },
        @{ Command="use exploit/windows/local/ms16_098_registry"; Description="MS16-098 Registry istismarı." },
        @{ Command="use exploit/windows/local/ms17_001_user_mode_code_exec"; Description="MS17-001 User Mode Code Execution istismarı." },
        @{ Command="use exploit/windows/local/cve_2021_36934_shadowvolumecopy"; Description="CVE-2021-36934 Shadow Volume Copy istismarı." },
        @{ Command="use exploit/multi/browser/firefox_proxy_prototype"; Description="Firefox Proxy Prototype istismarı." },
        @{ Command="use exploit/multi/browser/java_rhino"; Description="Java Rhino istismarı." },
        @{ Command="use exploit/multi/browser/java_atomicreferencearray"; Description="Java AtomicReferenceArray istismarı." },
        @{ Command="use exploit/multi/http/jboss_maindeployer"; Description="JBoss Main Deployer istismarı." },
        @{ Command="use exploit/multi/http/tomcat_mgr_deploy"; Description="Tomcat Manager Deploy istismarı." },
        @{ Command="use exploit/multi/http/jenkins_script_console"; Description="Jenkins Script Console istismarı." },
        @{ Command="use exploit/multi/http/struts2_namespace_ognl"; Description="Apache Struts2 Namespace OGNL istismarı." },
        @{ Command="use exploit/multi/http/struts_dmi_rest_exec"; Description="Apache Struts DMI REST OGNL istismarı." },
        @{ Command="use exploit/multi/http/apache_mod_cgi_bash_env_exec"; Description="Apache mod_cgi Bash environment variable komut enjeksiyonu." },
        @{ Command="use exploit/multi/http/apache_mod_isapi"; Description="Apache mod_isapi istismarı." },
        @{ Command="use exploit/multi/http/webdav_scstoragepathfromurl"; Description="WebDAV SCStoragePathFromUrl istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_sps"; Description="Adobe FlashPlayer SPS istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_newfunction"; Description="Adobe FlashPlayer NewFunction istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_convertlocaltoglobal"; Description="Adobe FlashPlayer ConvertLocalToGlobal istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_getlocalnames"; Description="Adobe FlashPlayer GetLocalNames istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_metadata"; Description="Adobe FlashPlayer Metadata istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_asnative"; Description="Adobe FlashPlayer ASNative istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_newclass"; Description="Adobe FlashPlayer NewClass istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_jbig2decode"; Description="Adobe FlashPlayer JBIG2Decode istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_regexvalue"; Description="Adobe FlashPlayer RegexValue istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_actionscript"; Description="Adobe FlashPlayer ActionScript istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_flashmedia"; Description="Adobe FlashPlayer FlashMedia istismarı." },
        @{ Command="use exploit/windows/fileformat/adobe_flashplayer_typeconfusion"; Description="Adobe FlashPlayer TypeConfusion istismarı." },
        @{ Command="use exploit/multi/http/struts2_code_exec_showcase"; Description="Apache Struts2 Showcase OGNL Kod Yürütme istismarı." },
        @{ Command="use exploit/multi/http/struts2_content_type"; Description="Apache Struts2 Content-Type istismarı." },
        @{ Command="use exploit/unix/webapp/drupal_drupageddon"; Description="Drupal Drupageddon istismarı." },
        @{ Command="use exploit/multi/http/jboss_invoke_deploy"; Description="JBoss JMXInvokerServlet Dosya Yükleme istismarı." },
        @{ Command="use exploit/windows/misc/hp_data_protector_cmd_exec"; Description="HP Data Protector komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_data_protector_restore"; Description="HP Data Protector restore istismarı." },
        @{ Command="use exploit/windows/misc/hp_data_protector_service"; Description="HP Data Protector servis istismarı." },
        @{ Command="use exploit/windows/misc/hp_data_protector_sendinfo"; Description="HP Data Protector SendInfo istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_ovw_authentication"; Description="HP OpenView NNM OvwAuthentication istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snnmp"; Description="HP OpenView NNM SNMP istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_auth"; Description="HP OpenView NNM SNMP Authentication istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_fd"; Description="HP OpenView NNM SNMP File Descriptor istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_inc"; Description="HP OpenView NNM SNMP increment istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_reply"; Description="HP OpenView NNM SNMP Reply istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_trap"; Description="HP OpenView NNM SNMP Trap istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_trap_auth"; Description="HP OpenView NNM SNMP Trap Authentication istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_trap_fd"; Description="HP OpenView NNM SNMP Trap File Descriptor istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_trap_inc"; Description="HP OpenView NNM SNMP Trap increment istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_trap_reply"; Description="HP OpenView NNM SNMP Trap Reply istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_snmp_trap_trunc"; Description="HP OpenView NNM SNMP Trap Truncation istismarı." },
        @{ Command="use exploit/windows/misc/hp_nnm_webappmon"; Description="HP OpenView NNM WebAppMon istismarı." },
        @{ Command="use exploit/windows/misc/hp_openview_ovtrace"; Description="HP OpenView NNM ovtrace istismarı." },
        @{ Command="use exploit/windows/misc/hp_openview_ovtrapd"; Description="HP OpenView NNM ovtrapd istismarı." },
        @{ Command="use exploit/windows/misc/hp_omniinetexec"; Description="HP OmniInetExec istismarı." },
        @{ Command="use exploit/windows/misc/hp_service_agent_cmd_exec"; Description="HP Service Agent komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_sitescope_cmd_exec"; Description="HP SiteScope komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_site_scope_java_deserialization"; Description="HP SiteScope Java Deserialization istismarı." },
        @{ Command="use exploit/windows/misc/hp_system_management_cmd_exec"; Description="HP System Management komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_system_management_dos"; Description="HP System Management DoS istismarı." },
        @{ Command="use exploit/windows/misc/hp_system_management_service"; Description="HP System Management Service istismarı." },
        @{ Command="use exploit/windows/misc/hp_system_management_tool"; Description="HP System Management Tool istismarı." },
        @{ Command="use exploit/windows/misc/hp_system_management_webapp"; Description="HP System Management WebApp istismarı." },
        @{ Command="use exploit/windows/misc/hp_virtual_connect_exec"; Description="HP Virtual Connect komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_virtual_connect_login"; Description="HP Virtual Connect login istismarı." },
        @{ Command="use exploit/windows/misc/hp_virtual_connect_service"; Description="HP Virtual Connect servis istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin"; Description="HP Web JetAdmin istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_cmd_exec"; Description="HP Web JetAdmin komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_file_upload"; Description="HP Web JetAdmin dosya yükleme istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_http"; Description="HP Web JetAdmin HTTP istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_login"; Description="HP Web JetAdmin login istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_ssl"; Description="HP Web JetAdmin SSL istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_udp"; Description="HP Web JetAdmin UDP istismarı." },
        @{ Command="use exploit/windows/misc/hp_web_jetadmin_webapp"; Description="HP Web JetAdmin WebApp istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_cmd_exec"; Description="HP WebInspect komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_http"; Description="HP WebInspect HTTP istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_service"; Description="HP WebInspect servis istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_ssl"; Description="HP WebInspect SSL istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_webapp"; Description="HP WebInspect WebApp istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xml"; Description="HP WebInspect XML istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xml_exec"; Description="HP WebInspect XML komut yürütme istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xml_upload"; Description="HP WebInspect XML dosya yükleme istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xml_validation"; Description="HP WebInspect XML doğrulama istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xml_webapp"; Description="HP WebInspect XML WebApp istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xml_xss"; Description="HP WebInspect XML XSS istismarı." },
        @{ Command="use exploit/windows/misc/hp_webinspect_xss_various"; Description="HP WebInspect XSS ve benzeri istismar varyasyonları." },
        @{ Command="use exploit/windows/local/cve_2022_26904_dpapi"; Description="CVE-2022-26904 DPAPI yetki yükseltme istismarı." },
        @{ Command="use exploit/windows/local/cve_2022_30190_msdt_follina"; Description="CVE-2022-30190 MSDT (Follina) uzaktan kod yürütme istismarı." },
        @{ Command="use exploit/windows/local/cve_2023_21768_win32k"; Description="CVE-2023-21768 Win32k yetki yükseltme istismarı." },
        @{ Command="use exploit/windows/misc/cve_2022_1472_zerologon"; Description="CVE-2020-1472 Zerologon etki alanı denetleyici istismarı." },
        @{ Command="use exploit/windows/misc/cve_2020_1302_printerdemon"; Description="CVE-2020-1302 Windows Printer Spooler LPE istismarı." },
        @{ Command="use exploit/linux/local/cve_2022_0847_dirtypipe"; Description="CVE-2022-0847 DirtyPipe yetki yükseltme istismarı (Linux)." },
        @{ Command="use exploit/linux/local/cve_2021_4034_pwnkit"; Description="CVE-2021-4034 Polkit (Pwnkit) yetki yükseltme istismarı." },
        @{ Command="use exploit/linux/http/cve_2022_1388_f5_bigip_auth_bypass"; Description="CVE-2022-1388 F5 BIG-IP kimlik doğrulama atlama ve RCE istismarı." },
        @{ Command="use exploit/multi/http/fortigate_auth_bypass"; Description="Fortigate kimlik doğrulama atlama istismarı." },
        @{ Command="use exploit/multi/http/spring4shell_rce"; Description="Spring4Shell RCE (CVE-2022-22965) istismarı." },
        @{ Command="use exploit/multi/http/cve_2022_22963_spring_cloud_function_spel_rce"; Description="Spring Cloud Function SpEL RCE (CVE-2022-22963) istismarı." },
        @{ Command="use exploit/linux/http/cacti_graph_realtime_rce"; Description="Cacti Realtime Graph RCE istismarı." }
    )
    

    $fzfInput = $msfCommands | ForEach-Object {
        "$([char]27)[38;5;57m$($_.Command)$([char]27)[0m`t$([char]27)[38;5;244m⯈ $($_.Description)$([char]27)[0m"
    } | Out-String

    $fzfOutputFile = [System.IO.Path]::GetTempFileName()

    $fzfInput | fzf --height 70% --layout=reverse --border --ansi --color=fg:#FFD700,bg:#1C1C1C,hl:#5F00AF --color=fg+:#FFD700,bg+:#262626,hl+:#7FFF00 --color=info:#00FF00,prompt:#00FF00,pointer:#FF0000,marker:#FF69B4,spinner:#00FF00,header:#00FF00 > $fzfOutputFile

    $selected = Get-Content -Path $fzfOutputFile

    if ($selected) {
        $selectedItem = $msfCommands | Where-Object { $_.Command -eq ($selected -split "`t")[0] }
        $selectedCommand = $selectedItem.Command
        $selectedDescription = $selectedItem.Description
        Clear-Host
        $prompt = " > "
        Write-Host "$prompt$selectedCommand   >  $selectedDescription" -ForegroundColor red
    }

    Remove-Item -Path $fzfOutputFile
}

Set-Alias msf Show-AnimatedMenu.Msfconsole
