function Show-AnimatedMenu.Nmap {
    $nmapCommands = @(
    @{ Command="nmap -sP 192.168.1.0/24"; Description="Ağdaki canlı cihazları tarar." },
    @{ Command="nmap -sS -p 22 192.168.1.1"; Description="Hedefteki 22 numaralı portu SYN taraması ile tarar." },
    @{ Command="nmap -A 192.168.1.1"; Description="Hedefteki OS ve servis versiyonlarını belirler." },
    @{ Command="nmap -sV 192.168.1.1"; Description="Hedefteki servis versiyonlarını belirler." },
    @{ Command="nmap -O 192.168.1.1"; Description="Hedefteki işletim sistemini tespit eder." },
    @{ Command="nmap -p- 192.168.1.1"; Description="Hedefteki tüm portları tarar." },
    @{ Command="nmap -v -A 192.168.1.1"; Description="Ayrıntılı bilgi ile tarar (verbose)." },
    @{ Command="nmap -sU -p 123 192.168.1.1"; Description="Hedefteki 123 numaralı UDP portunu tarar." },
    @{ Command="nmap --script vuln 192.168.1.1"; Description="Hedefteki bilinen güvenlik açıklarını kontrol eder." },
    @{ Command="nmap -sC 192.168.1.1"; Description="Hedefteki standart script taramasını gerçekleştirir." },
    @{ Command="nmap -Pn 192.168.1.1"; Description="Ping taraması yapmadan hedefi tarar." },
    @{ Command="nmap -T4 -A -v 192.168.1.1"; Description="Hızlı ve ayrıntılı tarama yapar." },
    @{ Command="nmap -sn 192.168.1.0/24"; Description="Sadece ping taraması yapar (port taraması yapmaz)." },
    @{ Command="nmap -oN output.txt 192.168.1.1"; Description="Taramayı normal metin formatında dosyaya kaydeder." },
    @{ Command="nmap -oX output.xml 192.168.1.1"; Description="Taramayı XML formatında dosyaya kaydeder." },
    @{ Command="nmap -oG output.gnmap 192.168.1.1"; Description="Taramayı grepable formatta dosyaya kaydeder." },
    @{ Command="nmap -p 80 --script http-sql-injection 192.168.1.1"; Description="HTTP SQL enjeksiyonu kontrolü yapar." },
    @{ Command="nmap -sI zombieHost 192.168.1.1"; Description="IP ID idle taraması yapar." },
    @{ Command="nmap -sW 192.168.1.1"; Description="TCP Windows taraması yapar." },
    @{ Command="nmap -sX 192.168.1.1"; Description="Xmas taraması yapar." },
    @{ Command="nmap -sF 192.168.1.1"; Description="FIN taraması yapar." },
    @{ Command="nmap -sN 192.168.1.1"; Description="TCP Null taraması yapar." },
    @{ Command="nmap -sR 192.168.1.1"; Description="RPC taraması yapar." },
    @{ Command="nmap --traceroute 192.168.1.1"; Description="Traceroute bilgilerini gösterir." },
    @{ Command="nmap -6 2001:db8::ff00:42:8329"; Description="IPv6 adresi üzerinde tarama yapar." },
    @{ Command="nmap -p 1-65535 192.168.1.1"; Description="Hedefteki tüm portları tarar (1-65535)." },
    @{ Command="nmap -p 80,443 192.168.1.1"; Description="Belirli portları (80 ve 443) tarar." },
    @{ Command="nmap -p 80 --open 192.168.1.1"; Description="Sadece açık olan belirli portları tarar (örnek: 80)." },
    @{ Command="nmap --script=default,safe 192.168.1.1"; Description="Varsayılan ve güvenli scriptleri çalıştırarak tarar." },
    @{ Command="nmap -sS -T4 -O -F --version-light 192.168.1.1"; Description="Hızlı ve hafif bir tarama yapar." },
    @{ Command="nmap --script discovery 192.168.1.0/24"; Description="Ağ keşfi scriptlerini çalıştırır." },
    @{ Command="nmap --script firewall-bypass 192.168.1.1"; Description="Güvenlik duvarı atlama scriptlerini çalıştırır." },
    @{ Command="nmap -sT 192.168.1.1"; Description="TCP Connect() taraması yapar." },
    @{ Command="nmap --reason 192.168.1.1"; Description="Taramadaki her sonucun nedenini açıklar." },
    @{ Command="nmap -sS -p- -sV -O --script vuln 192.168.1.1"; Description="Tüm portları tarar, servis versiyonlarını belirler, OS tespiti yapar ve bilinen güvenlik açıklarını kontrol eder." },
    @{ Command="nmap -p 80,443 --script ssl-cert 192.168.1.1"; Description="SSL sertifikalarını kontrol eder." },
    @{ Command="nmap -p 80 --script http-enum 192.168.1.1"; Description="HTTP servisleri ve dizinlerini enumerate eder." },
    @{ Command="nmap --script smb-os-discovery 192.168.1.1"; Description="SMB üzerinden OS keşfi yapar." },
    @{ Command="nmap -p 80 --script http-vuln-cve2017-5638 192.168.1.1"; Description="Apache Struts2 CVE-2017-5638 açığını kontrol eder." },
    @{ Command="nmap -p 21 --script ftp-anon 192.168.1.1"; Description="Anonim FTP girişini kontrol eder." },
    @{ Command="nmap -p 80 --script http-brute 192.168.1.1"; Description="HTTP brute force saldırısı yapar." },
    @{ Command="nmap -p 161 --script snmp-brute 192.168.1.1"; Description="SNMP brute force saldırısı yapar." },
    @{ Command="nmap -p 25 --script smtp-enum-users 192.168.1.1"; Description="SMTP kullanıcılarını enumerate eder." },
    @{ Command="nmap -p 53 --script dns-brute 192.168.1.1"; Description="DNS brute force saldırısı yapar." },
    @{ Command="nmap -p 1433 --script ms-sql-info 192.168.1.1"; Description="Microsoft SQL Server bilgilerini toplar." },
    @{ Command="nmap -p 3306 --script mysql-enum 192.168.1.1"; Description="MySQL bilgilerini enumerate eder." },
    @{ Command="nmap --script http-slowloris-check 192.168.1.1"; Description="HTTP Slowloris DoS açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms17-010 192.168.1.1"; Description="SMBv1 MS17-010 (EternalBlue) açığını kontrol eder." },
    @{ Command="nmap -p 80 --script http-robots.txt 192.168.1.1"; Description="robots.txt dosyasını kontrol eder." },
    @{ Command="nmap --script banner 192.168.1.1"; Description="Servis banner bilgilerini toplar." },
    @{ Command="nmap --script ssh-hostkey 192.168.1.1"; Description="SSH host anahtarlarını toplar." },
    @{ Command="nmap --script smb2-capabilities 192.168.1.1"; Description="SMB2 yeteneklerini kontrol eder." },
    @{ Command="nmap -p 80 --script http-title 192.168.1.1"; Description="HTTP başlıklarını toplar." },
    @{ Command="nmap -p 443 --script ssl-enum-ciphers 192.168.1.1"; Description="SSL şifreleme algoritmalarını enumerate eder." },
    @{ Command="nmap --script smtp-open-relay 192.168.1.1"; Description="SMTP open relay açığını kontrol eder." },
    @{ Command="nmap -p 445 --script smb-vuln-conficker 192.168.1.1"; Description="Conficker açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-regsvc-dos 192.168.1.1"; Description="SMB RegSvc DoS açığını kontrol eder." },
    @{ Command="nmap -p 161 --script snmp-info 192.168.1.1"; Description="SNMP bilgilerini toplar." },
    @{ Command="nmap -p 5900 --script vnc-info 192.168.1.1"; Description="VNC bilgilerini toplar." },
    @{ Command="nmap --script ipidseq 192.168.1.1"; Description="IP ID sıralamasını kontrol eder." },
    @{ Command="nmap -p 80 --script http-userdir-enum 192.168.1.1"; Description="HTTP kullanıcı dizinlerini enumerate eder." },
    @{ Command="nmap --script auth-spoof 192.168.1.1"; Description="Kimlik doğrulama sahtekarlığını kontrol eder." },
    @{ Command="nmap --script nfs-ls 192.168.1.1"; Description="NFS dizinlerini listeler." },
    @{ Command="nmap --script ssh-auth-methods 192.168.1.1"; Description="SSH kimlik doğrulama yöntemlerini kontrol eder." },
    @{ Command="nmap -p 445 --script smb-ls 192.168.1.1"; Description="SMB paylaşımlarını listeler." },
    @{ Command="nmap --script irc-info 192.168.1.1"; Description="IRC bilgilerini toplar." },
    @{ Command="nmap -p 443 --script ssl-cert-intaddr 192.168.1.1"; Description="SSL sertifikalarında iç IP adreslerini kontrol eder." },
    @{ Command="nmap --script snmp-sysdescr 192.168.1.1"; Description="SNMP sysDescr bilgisini toplar." }
    @{ Command="nmap -sn 10.0.0.0/24"; Description="Ağdaki canlı cihazları ICMP ile tarar." },
    @{ Command="nmap -sS -p 80 10.0.0.1"; Description="Hedefteki 80 numaralı portu SYN taraması ile tarar." },
    @{ Command="nmap -A 10.0.0.1"; Description="Hedefteki işletim sistemi ve servis versiyonlarını belirler." },
    @{ Command="nmap -sV 10.0.0.1"; Description="Hedefteki servis versiyonlarını belirler." },
    @{ Command="nmap -O 10.0.0.1"; Description="Hedefteki işletim sistemini tespit eder." },
    @{ Command="nmap -p- 10.0.0.1"; Description="Hedefteki tüm portları tarar." },
    @{ Command="nmap -v -A 10.0.0.1"; Description="Ayrıntılı bilgi ile tarar (verbose)." },
    @{ Command="nmap -sU -p 53 10.0.0.1"; Description="Hedefteki 53 numaralı UDP portunu tarar." },
    @{ Command="nmap --script vuln 10.0.0.1"; Description="Hedefteki bilinen güvenlik açıklarını kontrol eder." },
    @{ Command="nmap -sC 10.0.0.1"; Description="Hedefteki standart script taramasını gerçekleştirir." },
    @{ Command="nmap -Pn 10.0.0.1"; Description="Ping taraması yapmadan hedefi tarar." },
    @{ Command="nmap -T4 -A -v 10.0.0.1"; Description="Hızlı ve ayrıntılı tarama yapar." },
    @{ Command="nmap -sn 10.0.0.0/24"; Description="Sadece ping taraması yapar (port taraması yapmaz)." },
    @{ Command="nmap -oN output.txt 10.0.0.1"; Description="Taramayı normal metin formatında dosyaya kaydeder." },
    @{ Command="nmap -oX output.xml 10.0.0.1"; Description="Taramayı XML formatında dosyaya kaydeder." },
    @{ Command="nmap -oG output.gnmap 10.0.0.1"; Description="Taramayı grepable formatta dosyaya kaydeder." },
    @{ Command="nmap -p 8080 --script http-sql-injection 10.0.0.1"; Description="HTTP SQL enjeksiyonu kontrolü yapar." },
    @{ Command="nmap -sI zombieHost 10.0.0.1"; Description="IP ID idle taraması yapar." },
    @{ Command="nmap -sW 10.0.0.1"; Description="TCP Windows taraması yapar." },
    @{ Command="nmap -sX 10.0.0.1"; Description="Xmas taraması yapar." },
    @{ Command="nmap -sF 10.0.0.1"; Description="FIN taraması yapar." },
    @{ Command="nmap -sN 10.0.0.1"; Description="TCP Null taraması yapar." },
    @{ Command="nmap -sR 10.0.0.1"; Description="RPC taraması yapar." },
    @{ Command="nmap --traceroute 10.0.0.1"; Description="Traceroute bilgilerini gösterir." },
    @{ Command="nmap -6 2001:db8::ff00:42:8329"; Description="IPv6 adresi üzerinde tarama yapar." },
    @{ Command="nmap -p 1-10000 10.0.0.1"; Description="Hedefteki ilk 10000 portu tarar." },
    @{ Command="nmap -p 22,443 10.0.0.1"; Description="Belirli portları (22 ve 443) tarar." },
    @{ Command="nmap -p 22 --open 10.0.0.1"; Description="Sadece açık olan belirli portları tarar (örnek: 22)." },
    @{ Command="nmap --script=default,safe 10.0.0.1"; Description="Varsayılan ve güvenli scriptleri çalıştırarak tarar." },
    @{ Command="nmap -sS -T4 -O -F --version-light 10.0.0.1"; Description="Hızlı ve hafif bir tarama yapar." },
    @{ Command="nmap --script discovery 10.0.0.0/24"; Description="Ağ keşfi scriptlerini çalıştırır." },
    @{ Command="nmap --script firewall-bypass 10.0.0.1"; Description="Güvenlik duvarı atlama scriptlerini çalıştırır." },
    @{ Command="nmap -sT 10.0.0.1"; Description="TCP Connect() taraması yapar." },
    @{ Command="nmap --reason 10.0.0.1"; Description="Taramadaki her sonucun nedenini açıklar." },
    @{ Command="nmap -sS -p- -sV -O --script vuln 10.0.0.1"; Description="Tüm portları tarar, servis versiyonlarını belirler, OS tespiti yapar ve bilinen güvenlik açıklarını kontrol eder." },
    @{ Command="nmap -p 80,443 --script ssl-cert 10.0.0.1"; Description="SSL sertifikalarını kontrol eder." },
    @{ Command="nmap -p 80 --script http-enum 10.0.0.1"; Description="HTTP servisleri ve dizinlerini enumerate eder." },
    @{ Command="nmap --script smb-os-discovery 10.0.0.1"; Description="SMB üzerinden OS keşfi yapar." },
    @{ Command="nmap -p 80 --script http-vuln-cve2017-5638 10.0.0.1"; Description="Apache Struts2 CVE-2017-5638 açığını kontrol eder." },
    @{ Command="nmap -p 21 --script ftp-anon 10.0.0.1"; Description="Anonim FTP girişini kontrol eder." },
    @{ Command="nmap -p 80 --script http-brute 10.0.0.1"; Description="HTTP brute force saldırısı yapar." },
    @{ Command="nmap -p 161 --script snmp-brute 10.0.0.1"; Description="SNMP brute force saldırısı yapar." },
    @{ Command="nmap -p 25 --script smtp-enum-users 10.0.0.1"; Description="SMTP kullanıcılarını enumerate eder." },
    @{ Command="nmap -p 53 --script dns-brute 10.0.0.1"; Description="DNS brute force saldırısı yapar." },
    @{ Command="nmap -p 1433 --script ms-sql-info 10.0.0.1"; Description="Microsoft SQL Server bilgilerini toplar." },
    @{ Command="nmap -p 3306 --script mysql-enum 10.0.0.1"; Description="MySQL bilgilerini enumerate eder." },
    @{ Command="nmap --script http-slowloris-check 10.0.0.1"; Description="HTTP Slowloris DoS açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms17-010 10.0.0.1"; Description="SMBv1 MS17-010 (EternalBlue) açığını kontrol eder." },
    @{ Command="nmap -p 80 --script http-robots.txt 10.0.0.1"; Description="robots.txt dosyasını kontrol eder." },
    @{ Command="nmap --script banner 10.0.0.1"; Description="Servis banner bilgilerini toplar." },
    @{ Command="nmap --script ssh-hostkey 10.0.0.1"; Description="SSH host anahtarlarını toplar." },
    @{ Command="nmap --script smb2-capabilities 10.0.0.1"; Description="SMB2 yeteneklerini kontrol eder." },
    @{ Command="nmap -p 80 --script http-title 10.0.0.1"; Description="HTTP başlıklarını toplar." },
    @{ Command="nmap -p 443 --script ssl-enum-ciphers 10.0.0.1"; Description="SSL şifreleme algoritmalarını enumerate eder." },
    @{ Command="nmap --script smtp-open-relay 10.0.0.1"; Description="SMTP open relay açığını kontrol eder." },
    @{ Command="nmap -p 445 --script smb-vuln-conficker 10.0.0.1"; Description="Conficker açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-regsvc-dos 10.0.0.1"; Description="SMB RegSvc DoS açığını kontrol eder." },
    @{ Command="nmap -p 161 --script snmp-info 10.0.0.1"; Description="SNMP bilgilerini toplar." },
    @{ Command="nmap -p 5900 --script vnc-info 10.0.0.1"; Description="VNC bilgilerini toplar." },
    @{ Command="nmap --script ipidseq 10.0.0.1"; Description="IP ID sıralamasını kontrol eder." },
    @{ Command="nmap -p 80 --script http-userdir-enum 10.0.0.1"; Description="HTTP kullanıcı dizinlerini enumerate eder." },
    @{ Command="nmap --script auth-spoof 10.0.0.1"; Description="Kimlik doğrulama sahtekarlığını kontrol eder." },
    @{ Command="nmap --script nfs-ls 10.0.0.1"; Description="NFS dizinlerini listeler." },
    @{ Command="nmap --script ssh-auth-methods 10.0.0.1"; Description="SSH kimlik doğrulama yöntemlerini kontrol eder." },
    @{ Command="nmap -p 445 --script smb-ls 10.0.0.1"; Description="SMB paylaşımlarını listeler." },
    @{ Command="nmap --script irc-info 10.0.0.1"; Description="IRC bilgilerini toplar." },
    @{ Command="nmap -p 443 --script ssl-cert-intaddr 10.0.0.1"; Description="SSL sertifikalarında iç IP adreslerini kontrol eder." },
    @{ Command="nmap --script snmp-sysdescr 10.0.0.1"; Description="SNMP sysDescr bilgisini toplar." },
    @{ Command="nmap --script http-internal-ip-disclosure 10.0.0.1"; Description="HTTP iç IP adresi sızmasını kontrol eder." },
    @{ Command="nmap --script http-git 10.0.0.1"; Description="HTTP git deposunu kontrol eder." },
    @{ Command="nmap --script http-dombased-xss 10.0.0.1"; Description="HTTP DOM tabanlı XSS açığını kontrol eder." },
    @{ Command="nmap --script http-fileupload-exploiter 10.0.0.1"; Description="HTTP dosya yükleme zafiyetini kontrol eder." },
    @{ Command="nmap --script http-php-version 10.0.0.1"; Description="HTTP PHP versiyonunu kontrol eder." },
    @{ Command="nmap --script http-wordpress-users 10.0.0.1"; Description="HTTP WordPress kullanıcılarını kontrol eder." },
    @{ Command="nmap --script http-joomla-brute 10.0.0.1"; Description="HTTP Joomla brute force saldırısı yapar." },
    @{ Command="nmap --script http-drupal-enum 10.0.0.1"; Description="HTTP Drupal kullanıcılarını enumerate eder." },
    @{ Command="nmap --script http-xssed 10.0.0.1"; Description="HTTP XSS sızmasını kontrol eder." },
    @{ Command="nmap --script http-aspnet-debug 10.0.0.1"; Description="HTTP ASP.NET debug modunu kontrol eder." },
    @{ Command="nmap --script http-security-headers 10.0.0.1"; Description="HTTP güvenlik başlıklarını kontrol eder." },
    @{ Command="nmap --script http-method-tamper 10.0.0.1"; Description="HTTP metod değiştirme zafiyetini kontrol eder." },
    @{ Command="nmap --script http-cors 10.0.0.1"; Description="HTTP CORS zafiyetini kontrol eder." },
    @{ Command="nmap --script http-vmware-path-vuln 10.0.0.1"; Description="HTTP VMware yol açığını kontrol eder." },
    @{ Command="nmap --script http-enum 10.0.0.1"; Description="HTTP hizmetlerini enumerate eder." },
    @{ Command="nmap --script http-form-brute 10.0.0.1"; Description="HTTP form brute force saldırısı yapar." },
    @{ Command="nmap --script http-headers 10.0.0.1"; Description="HTTP başlıklarını toplar." },
    @{ Command="nmap --script http-huawei-hg5xx-vuln 10.0.0.1"; Description="HTTP Huawei HG5xx açığını kontrol eder." },
    @{ Command="nmap --script http-iis-short-name-brute 10.0.0.1"; Description="HTTP IIS kısa isim brute force saldırısı yapar." },
    @{ Command="nmap --script http-open-redirect 10.0.0.1"; Description="HTTP açık yönlendirme zafiyetini kontrol eder." },
    @{ Command="nmap --script http-rfi-spider 10.0.0.1"; Description="HTTP RFI spider açığını kontrol eder." },
    @{ Command="nmap --script http-sitemap-generator 10.0.0.1"; Description="HTTP site haritası oluşturur." },
    @{ Command="nmap --script http-waf-fingerprint 10.0.0.1"; Description="HTTP WAF parmak izi belirler." },
    @{ Command="nmap --script http-brute 10.0.0.1"; Description="HTTP brute force saldırısı yapar." },
    @{ Command="nmap --script http-robots 10.0.0.1"; Description="HTTP robots.txt dosyasını kontrol eder." },
    @{ Command="nmap --script http-title 10.0.0.1"; Description="HTTP başlıklarını toplar." },
    @{ Command="nmap --script http-useragent-tester 10.0.0.1"; Description="HTTP User-Agent test eder." },
    @{ Command="nmap --script http-wordpress-brute 10.0.0.1"; Description="HTTP WordPress brute force saldırısı yapar." },
    @{ Command="nmap --script http-xss-finder 10.0.0.1"; Description="HTTP XSS açığını bulur." },
    @{ Command="nmap --script mysql-brute 10.0.0.1"; Description="MySQL brute force saldırısı yapar." },
    @{ Command="nmap --script mysql-databases 10.0.0.1"; Description="MySQL veri tabanlarını enumerate eder." },
    @{ Command="nmap --script mysql-info 10.0.0.1"; Description="MySQL bilgilerini toplar." },
    @{ Command="nmap --script mysql-variables 10.0.0.1"; Description="MySQL değişkenlerini toplar." },
    @{ Command="nmap --script ssh-brute 10.0.0.1"; Description="SSH brute force saldırısı yapar." }
    @{ Command="nmap --script ssh-auth-methods 10.0.0.1"; Description="SSH kimlik doğrulama yöntemlerini kontrol eder." },
    @{ Command="nmap --script ssh-hostkey 10.0.0.1"; Description="SSH host anahtarlarını toplar." },
    @{ Command="nmap --script ssh-publickey-acceptance 10.0.0.1"; Description="SSH public key kabulünü kontrol eder." },
    @{ Command="nmap --script sshv1 10.0.0.1"; Description="SSHv1 servisini kontrol eder." },
    @{ Command="nmap --script ftp-brute 10.0.0.1"; Description="FTP brute force saldırısı yapar." },
    @{ Command="nmap --script ftp-anon 10.0.0.1"; Description="Anonim FTP girişini kontrol eder." },
    @{ Command="nmap --script ftp-libopie 10.0.0.1"; Description="FTP libopie zafiyetini kontrol eder." },
    @{ Command="nmap --script ftp-proftpd-backdoor 10.0.0.1"; Description="ProFTPD backdoor zafiyetini kontrol eder." },
    @{ Command="nmap --script ftp-vsftpd-backdoor 10.0.0.1"; Description="vsFTPd backdoor zafiyetini kontrol eder." },
    @{ Command="nmap --script ftp-vuln-cve2010-4221 10.0.0.1"; Description="FTP CVE-2010-4221 açığını kontrol eder." },
    @{ Command="nmap --script smb-brute 10.0.0.1"; Description="SMB brute force saldırısı yapar." },
    @{ Command="nmap --script smb-enum-shares 10.0.0.1"; Description="SMB paylaşımlarını enumerate eder." },
    @{ Command="nmap --script smb-enum-users 10.0.0.1"; Description="SMB kullanıcılarını enumerate eder." },
    @{ Command="nmap --script smb-ls 10.0.0.1"; Description="SMB dizinlerini listeler." },
    @{ Command="nmap --script smb-mbenum 10.0.0.1"; Description="SMB Master Browser bilgilerini toplar." },
    @{ Command="nmap --script smb-os-discovery 10.0.0.1"; Description="SMB üzerinden işletim sistemini keşfeder." },
    @{ Command="nmap --script smb-protocols 10.0.0.1"; Description="SMB protokollerini kontrol eder." },
    @{ Command="nmap --script smb-security-mode 10.0.0.1"; Description="SMB güvenlik modunu kontrol eder." },
    @{ Command="nmap --script smb-server-stats 10.0.0.1"; Description="SMB sunucu istatistiklerini toplar." },
    @{ Command="nmap --script smb-system-info 10.0.0.1"; Description="SMB sistem bilgilerini toplar." },
    @{ Command="nmap --script smb-vuln-conficker 10.0.0.1"; Description="Conficker açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-cve-2017-7494 10.0.0.1"; Description="SMB CVE-2017-7494 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms08-067 10.0.0.1"; Description="MS08-067 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms10-054 10.0.0.1"; Description="MS10-054 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms10-061 10.0.0.1"; Description="MS10-061 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms17-010 10.0.0.1"; Description="SMBv1 MS17-010 (EternalBlue) açığını kontrol eder." },
    @{ Command="nmap --script smb2-capabilities 10.0.0.1"; Description="SMB2 yeteneklerini kontrol eder." },
    @{ Command="nmap --script smb2-security-mode 10.0.0.1"; Description="SMB2 güvenlik modunu kontrol eder." },
    @{ Command="nmap --script smb2-time 10.0.0.1"; Description="SMB2 zaman bilgilerini kontrol eder." },
    @{ Command="nmap --script dns-brute 10.0.0.1"; Description="DNS brute force saldırısı yapar." },
    @{ Command="nmap --script dns-cache-snoop 10.0.0.1"; Description="DNS cache snooping yapar." },
    @{ Command="nmap --script dns-check-zone 10.0.0.1"; Description="DNS zone transfer zafiyetini kontrol eder." },
    @{ Command="nmap --script dns-ip6-arpa-scan 10.0.0.1"; Description="IPv6 reverse DNS taraması yapar." },
    @{ Command="nmap --script dns-nsid 10.0.0.1"; Description="DNS NSID bilgilerini toplar." },
    @{ Command="nmap --script dns-srv-enum 10.0.0.1"; Description="DNS SRV kayıtlarını enumerate eder." },
    @{ Command="nmap --script dns-zone-transfer 10.0.0.1"; Description="DNS zone transfer zafiyetini kontrol eder." },
    @{ Command="nmap --script ssl-cert 10.0.0.1"; Description="SSL sertifikalarını kontrol eder." },
    @{ Command="nmap --script ssl-enum-ciphers 10.0.0.1"; Description="SSL şifreleme algoritmalarını enumerate eder." },
    @{ Command="nmap --script ssl-known-key 10.0.0.1"; Description="Bilinen SSL anahtarlarını kontrol eder." },
    @{ Command="nmap --script ssl-poodle 10.0.0.1"; Description="SSL POODLE açığını kontrol eder." },
    @{ Command="nmap --script sslv2 10.0.0.1"; Description="SSlv2 destekleyen servisleri kontrol eder." },
    @{ Command="nmap --script sslv2-drown 10.0.0.1"; Description="SSLv2 DROWN açığını kontrol eder." },
    @{ Command="nmap --script sslv3 10.0.0.1"; Description="SSLv3 destekleyen servisleri kontrol eder." },
    @{ Command="nmap --script tls-nextprotoneg 10.0.0.1"; Description="TLS Next Protocol Negotiation desteğini kontrol eder." },
    @{ Command="nmap --script tls-ticketbleed 10.0.0.1"; Description="TLS Ticketbleed açığını kontrol eder." },
    @{ Command="nmap --script tls-heartbleed 10.0.0.1"; Description="TLS Heartbleed açığını kontrol eder." },
    @{ Command="nmap --script tls-known-key 10.0.0.1"; Description="Bilinen TLS anahtarlarını kontrol eder." },
    @{ Command="nmap --script tls-poodle 10.0.0.1"; Description="TLS POODLE açığını kontrol eder." },
    @{ Command="nmap --script tls-ticketbleed 10.0.0.1"; Description="TLS Ticketbleed açığını kontrol eder." },
    @{ Command="nmap --script http-enum 10.0.0.1"; Description="HTTP servislerini enumerate eder." },
    @{ Command="nmap --script http-methods 10.0.0.1"; Description="HTTP metodlarını kontrol eder." },
    @{ Command="nmap --script http-headers 10.0.0.1"; Description="HTTP başlıklarını toplar." },
    @{ Command="nmap --script http-title 10.0.0.1"; Description="HTTP başlıklarını toplar." },
    @{ Command="nmap --script http-auth 10.0.0.1"; Description="HTTP kimlik doğrulama bilgilerini toplar." },
    @{ Command="nmap --script http-cors 10.0.0.1"; Description="HTTP CORS zafiyetini kontrol eder." },
    @{ Command="nmap --script http-internal-ip-disclosure 10.0.0.1"; Description="HTTP iç IP adresi sızmasını kontrol eder." },
    @{ Command="nmap --script http-open-redirect 10.0.0.1"; Description="HTTP açık yönlendirme zafiyetini kontrol eder." },
    @{ Command="nmap --script http-php-version 10.0.0.1"; Description="HTTP PHP versiyonunu kontrol eder." },
    @{ Command="nmap --script http-security-headers 10.0.0.1"; Description="HTTP güvenlik başlıklarını kontrol eder." },
    @{ Command="nmap --script http-useragent-tester 10.0.0.1"; Description="HTTP User-Agent test eder." },
    @{ Command="nmap --script http-wordpress-users 10.0.0.1"; Description="HTTP WordPress kullanıcılarını kontrol eder." },
    @{ Command="nmap --script http-joomla-brute 10.0.0.1"; Description="HTTP Joomla brute force saldırısı yapar." },
    @{ Command="nmap --script http-drupal-enum 10.0.0.1"; Description="HTTP Drupal kullanıcılarını enumerate eder." },
    @{ Command="nmap --script http-xssed 10.0.0.1"; Description="HTTP XSS sızmasını kontrol eder." },
    @{ Command="nmap --script http-vmware-path-vuln 10.0.0.1"; Description="HTTP VMware yol açığını kontrol eder." },
    @{ Command="nmap --script http-waf-detect 10.0.0.1"; Description="HTTP WAF varlığını tespit eder." },
    @{ Command="nmap --script http-waf-fingerprint 10.0.0.1"; Description="HTTP WAF parmak izi belirler." },
    @{ Command="nmap --script mysql-brute 10.0.0.1"; Description="MySQL brute force saldırısı yapar." },
    @{ Command="nmap --script mysql-databases 10.0.0.1"; Description="MySQL veri tabanlarını enumerate eder." },
    @{ Command="nmap --script mysql-empty-password 10.0.0.1"; Description="MySQL boş şifre kontrolü yapar." },
    @{ Command="nmap --script mysql-info 10.0.0.1"; Description="MySQL bilgilerini toplar." },
    @{ Command="nmap --script mysql-variables 10.0.0.1"; Description="MySQL değişkenlerini toplar." },
    @{ Command="nmap --script mysql-query 10.0.0.1"; Description="MySQL sorguları çalıştırır." },
    @{ Command="nmap --script mysql-enum 10.0.0.1"; Description="MySQL kullanıcılarını enumerate eder." },
    @{ Command="nmap --script mysql-audit 10.0.0.1"; Description="MySQL denetim yapar." },
    @{ Command="nmap --script mysql-info 10.0.0.1"; Description="MySQL versiyon ve yapılandırma bilgilerini toplar." },
    @{ Command="nmap --script mysql-users 10.0.0.1"; Description="MySQL kullanıcılarını kontrol eder." },
    @{ Command="nmap --script mysql-tables 10.0.0.1"; Description="MySQL tablolarını enumerate eder." },
    @{ Command="nmap --script mysql-databases 10.0.0.1"; Description="MySQL veri tabanlarını kontrol eder." },
    @{ Command="nmap --script mysql-rdbms-info 10.0.0.1"; Description="MySQL RDBMS bilgilerini toplar." },
    @{ Command="nmap --script mysql-users 10.0.0.1"; Description="MySQL kullanıcılarını enumerate eder." },
    @{ Command="nmap --script oracle-brute 10.0.0.1"; Description="Oracle brute force saldırısı yapar." },
    @{ Command="nmap --script oracle-databases 10.0.0.1"; Description="Oracle veri tabanlarını enumerate eder." },
    @{ Command="nmap --script oracle-enum-users 10.0.0.1"; Description="Oracle kullanıcılarını enumerate eder." },
    @{ Command="nmap --script oracle-sid-brute 10.0.0.1"; Description="Oracle SID brute force saldırısı yapar." },
    @{ Command="nmap --script oracle-tns-version 10.0.0.1"; Description="Oracle TNS versiyonunu kontrol eder." },
    @{ Command="nmap --script postgresql-brute 10.0.0.1"; Description="PostgreSQL brute force saldırısı yapar." },
    @{ Command="nmap --script postgresql-databases 10.0.0.1"; Description="PostgreSQL veri tabanlarını enumerate eder." },
    @{ Command="nmap --script postgresql-enum 10.0.0.1"; Description="PostgreSQL kullanıcılarını ve haklarını enumerate eder." },
    @{ Command="nmap --script postgresql-info 10.0.0.1"; Description="PostgreSQL versiyon ve yapılandırma bilgilerini toplar." },
    @{ Command="nmap --script postgresql-query 10.0.0.1"; Description="PostgreSQL sorguları çalıştırır." },
    @{ Command="nmap --script postgresql-users 10.0.0.1"; Description="PostgreSQL kullanıcılarını enumerate eder." },
    @{ Command="nmap --script postgresql-tables 10.0.0.1"; Description="PostgreSQL tablolarını enumerate eder." },
    @{ Command="nmap --script redis-brute 10.0.0.1"; Description="Redis brute force saldırısı yapar." },
    @{ Command="nmap --script redis-info 10.0.0.1"; Description="Redis versiyon ve yapılandırma bilgilerini toplar." },
    @{ Command="nmap --script redis-databases 10.0.0.1"; Description="Redis veri tabanlarını enumerate eder." },
    @{ Command="nmap --script redis-users 10.0.0.1"; Description="Redis kullanıcılarını enumerate eder." },
    @{ Command="nmap --script mongodb-brute 10.0.0.1"; Description="MongoDB brute force saldırısı yapar." },
    @{ Command="nmap --script mongodb-databases 10.0.0.1"; Description="MongoDB veri tabanlarını enumerate eder." },
    @{ Command="nmap --script mongodb-users 10.0.0.1"; Description="MongoDB kullanıcılarını enumerate eder." },
    @{ Command="nmap --script mongodb-info 10.0.0.1"; Description="MongoDB versiyon ve yapılandırma bilgilerini toplar." },
    @{ Command="nmap --script snmp-brute 10.0.0.1"; Description="SNMP brute force saldırısı yapar." },
    @{ Command="nmap --script snmp-info 10.0.0.1"; Description="SNMP bilgilerini toplar." },
    @{ Command="nmap --script snmp-hh3c-brute 10.0.0.1"; Description="SNMP HH3C brute force saldırısı yapar." },
    @{ Command="nmap --script snmp-interfaces 10.0.0.1"; Description="SNMP arayüz bilgilerini toplar." },
    @{ Command="nmap --script snmp-ios-config 10.0.0.1"; Description="SNMP IOS yapılandırma bilgilerini toplar." },
    @{ Command="nmap --script snmp-ios-fw 10.0.0.1"; Description="SNMP IOS firewall bilgilerini toplar." },
    @{ Command="nmap --script snmp-ios-routes 10.0.0.1"; Description="SNMP IOS route bilgilerini toplar." },
    @{ Command="nmap --script snmp-netstat 10.0.0.1"; Description="SNMP Netstat bilgilerini toplar." },
    @{ Command="nmap --script snmp-processes 10.0.0.1"; Description="SNMP process bilgilerini toplar." },
    @{ Command="nmap --script snmp-sysdescr 10.0.0.1"; Description="SNMP sysDescr bilgisini toplar." },
    @{ Command="nmap --script snmp-win32-accounts 10.0.0.1"; Description="SNMP Win32 hesap bilgilerini toplar." },
    @{ Command="nmap --script snmp-win32-services 10.0.0.1"; Description="SNMP Win32 servis bilgilerini toplar." },
    @{ Command="nmap --script snmp-win32-shares 10.0.0.1"; Description="SNMP Win32 paylaşım bilgilerini toplar." },
    @{ Command="nmap --script snmp-win32-software 10.0.0.1"; Description="SNMP Win32 yazılım bilgilerini toplar." },
    @{ Command="nmap --script snmp-win32-storage 10.0.0.1"; Description="SNMP Win32 depolama bilgilerini toplar." },
    @{ Command="nmap --script snmp-win32-users 10.0.0.1"; Description="SNMP Win32 kullanıcı bilgilerini toplar." },
    @{ Command="nmap --script smtp-brute 10.0.0.1"; Description="SMTP brute force saldırısı yapar." },
    @{ Command="nmap --script smtp-enum-users 10.0.0.1"; Description="SMTP kullanıcılarını enumerate eder." },
    @{ Command="nmap --script smtp-open-relay 10.0.0.1"; Description="SMTP open relay açığını kontrol eder." },
    @{ Command="nmap --script smtp-strangeport 10.0.0.1"; Description="SMTP sıradışı port kontrolü yapar." },
    @{ Command="nmap --script smtp-commands 10.0.0.1"; Description="SMTP komutlarını kontrol eder." },
    @{ Command="nmap --script smtp-vuln-cve2011-1764 10.0.0.1"; Description="SMTP CVE-2011-1764 açığını kontrol eder." },
    @{ Command="nmap --script imap-brute 10.0.0.1"; Description="IMAP brute force saldırısı yapar." },
    @{ Command="nmap --script imap-capabilities 10.0.0.1"; Description="IMAP yeteneklerini kontrol eder." },
    @{ Command="nmap --script imap-ntlm-info 10.0.0.1"; Description="IMAP NTLM bilgilerini toplar." },
    @{ Command="nmap --script pop3-brute 10.0.0.1"; Description="POP3 brute force saldırısı yapar." },
    @{ Command="nmap --script pop3-capabilities 10.0.0.1"; Description="POP3 yeteneklerini kontrol eder." },
    @{ Command="nmap --script pop3-ntlm-info 10.0.0.1"; Description="POP3 NTLM bilgilerini toplar." },
    @{ Command="nmap --script pop3-login-brute 10.0.0.1"; Description="POP3 login brute force saldırısı yapar." },
    @{ Command="nmap --script pop3-login-enum 10.0.0.1"; Description="POP3 login bilgilerini enumerate eder." },
    @{ Command="nmap --script pop3-mail-enum 10.0.0.1"; Description="POP3 mail bilgilerini enumerate eder." },
    @{ Command="nmap --script smb-brute 10.0.0.1"; Description="SMB brute force saldırısı yapar." },
    @{ Command="nmap --script smb-enum-shares 10.0.0.1"; Description="SMB paylaşımlarını enumerate eder." },
    @{ Command="nmap --script smb-enum-users 10.0.0.1"; Description="SMB kullanıcılarını enumerate eder." },
    @{ Command="nmap --script smb-ls 10.0.0.1"; Description="SMB dizinlerini listeler." },
    @{ Command="nmap --script smb-mbenum 10.0.0.1"; Description="SMB Master Browser bilgilerini toplar." },
    @{ Command="nmap --script smb-os-discovery 10.0.0.1"; Description="SMB üzerinden işletim sistemini keşfeder." },
    @{ Command="nmap --script smb-protocols 10.0.0.1"; Description="SMB protokollerini kontrol eder." },
    @{ Command="nmap --script smb-security-mode 10.0.0.1"; Description="SMB güvenlik modunu kontrol eder." },
    @{ Command="nmap --script smb-server-stats 10.0.0.1"; Description="SMB sunucu istatistiklerini toplar." },
    @{ Command="nmap --script smb-system-info 10.0.0.1"; Description="SMB sistem bilgilerini toplar." },
    @{ Command="nmap --script smb-vuln-conficker 10.0.0.1"; Description="Conficker açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-cve-2017-7494 10.0.0.1"; Description="SMB CVE-2017-7494 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms08-067 10.0.0.1"; Description="MS08-067 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms10-054 10.0.0.1"; Description="MS10-054 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms10-061 10.0.0.1"; Description="MS10-061 açığını kontrol eder." },
    @{ Command="nmap --script smb-vuln-ms17-010 10.0.0.1"; Description="SMBv1 MS17-010 (EternalBlue) açığını kontrol eder." },
    @{ Command="nmap --script smb2-capabilities 10.0.0.1"; Description="SMB2 yeteneklerini kontrol eder." },
    @{ Command="nmap --script smb2-security-mode 10.0.0.1"; Description="SMB2 güvenlik modunu kontrol eder." },
    @{ Command="nmap --script smb2-time 10.0.0.1"; Description="SMB2 zaman bilgilerini kontrol eder." },
    @{ Command="nmap --script ssl-cert 10.0.0.1"; Description="SSL sertifikalarını kontrol eder." },
    @{ Command="nmap --script ssl-enum-ciphers 10.0.0.1"; Description="SSL şifreleme algoritmalarını enumerate eder." },
    @{ Command="nmap --script ssl-known-key 10.0.0.1"; Description="Bilinen SSL anahtarlarını kontrol eder." },
    @{ Command="nmap --script ssl-poodle 10.0.0.1"; Description="SSL POODLE açığını kontrol eder." },
    @{ Command="nmap --script sslv2 10.0.0.1"; Description="SSlv2 destekleyen servisleri kontrol eder." },
    @{ Command="nmap --script sslv2-drown 10.0.0.1"; Description="SSLv2 DROWN açığını kontrol eder." },
    @{ Command="nmap --script sslv3 10.0.0.1"; Description="SSLv3 destekleyen servisleri kontrol eder." },
    @{ Command="nmap --script tls-nextprotoneg 10.0.0.1"; Description="TLS Next Protocol Negotiation desteğini kontrol eder." },
    @{ Command="nmap --script tls-ticketbleed 10.0.0.1"; Description="TLS Ticketbleed açığını kontrol eder." },
    @{ Command="nmap --script tls-heartbleed 10.0.0.1"; Description="TLS Heartbleed açığını kontrol eder." },
    @{ Command="nmap --script tls-known-key 10.0.0.1"; Description="Bilinen TLS anahtarlarını kontrol eder." },
    @{ Command="nmap --script tls-poodle 10.0.0.1"; Description="TLS POODLE açığını kontrol eder." },
    @{ Command="nmap --script tls-ticketbleed 10.0.0.1"; Description="TLS Ticketbleed açığını kontrol eder." },
    @{ Command="nmap --script dns-brute 10.0.0.1"; Description="DNS brute force saldırısı yapar." },
    @{ Command="nmap --script dns-cache-snoop 10.0.0.1"; Description="DNS cache snooping yapar." },
    @{ Command="nmap --script dns-check-zone 10.0.0.1"; Description="DNS zone transfer zafiyetini kontrol eder." },
    @{ Command="nmap --script dns-ip6-arpa-scan 10.0.0.1"; Description="IPv6 reverse DNS taraması yapar." },
    @{ Command="nmap --script dns-nsid 10.0.0.1"; Description="DNS NSID bilgilerini toplar." },
    @{ Command="nmap --script dns-srv-enum 10.0.0.1"; Description="DNS SRV kayıtlarını enumerate eder." },
    @{ Command="nmap --script dns-zone-transfer 10.0.0.1"; Description="DNS zone transfer zafiyetini kontrol eder." }
    )

    $fzfInput = $nmapCommands | ForEach-Object {
        "$([char]27)[38;5;57m$($_.Command)$([char]27)[0m`t$([char]27)[38;5;244m⯈ $($_.Description)$([char]27)[0m"
    } | Out-String

    $fzfOutputFile = [System.IO.Path]::GetTempFileName()

    $fzfInput | fzf --height 70% --layout=reverse --border --ansi --color=fg:#FFD700,bg:#1C1C1C,hl:#5F00AF --color=fg+:#FFD700,bg+:#262626,hl+:#7FFF00 --color=info:#00FF00,prompt:#00FF00,pointer:#FF0000,marker:#FF69B4,spinner:#00FF00,header:#00FF00 > $fzfOutputFile

    $selected = Get-Content -Path $fzfOutputFile

    if ($selected) {
        $selectedItem = $nmapCommands | Where-Object { $_.Command -eq ($selected -split "`t")[0] }
        $selectedCommand = $selectedItem.Command
        $selectedDescription = $selectedItem.Description
        Clear-Host
        $prompt = " > "
        Write-Host "$prompt$selectedCommand   >  $selectedDescription" -ForegroundColor red
    }

    Remove-Item -Path $fzfOutputFile
}

Set-Alias nmp Show-AnimatedMenu.Nmap